-- =====================================================
-- RETROUVONSLES - DÉSACTIVER RLS COMPLÈTEMENT (TEST)
-- Exécutez ce script pour vérifier si le problème vient bien de RLS
-- =====================================================

-- Désactiver RLS sur TOUTES les tables
ALTER TABLE IF EXISTS resultat_ia DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organisation DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notification DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS utilisateur DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS signalement DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS dossier_disparition DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS alerte DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS photo DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS commentaire DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS document DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS personne DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS localisation DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lien_filiation DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS utilisateur_role DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS role DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS journal_activite DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS statistique_recherche DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS don DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS campagne_sensibilisation DISABLE ROW LEVEL SECURITY;

-- Vérifier l'état de RLS sur toutes les tables
SELECT 
    schemaname,
    tablename,
    rowsecurity
FROM pg_tables 
WHERE schemaname = 'public'
ORDER BY tablename;

SELECT 'RLS désactivé sur toutes les tables!' AS status;
